// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Get current domain for OAuth redirect
const SITE_URL = import.meta.env.DEV 
  ? 'http://localhost:5173'
  : 'https://money-note.vercel.app'; // Vercel 도메인으로 변경해주세요

const REDIRECT_URL = `${SITE_URL}/auth/callback`;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    flowType: 'pkce',
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'x-redirect-url': REDIRECT_URL,
    },
  },
});